---
ID: "de009619-ce38-4a6a-9261-92dd914f5458"
Parent: "a31bcb73-20a9-4bc2-91d8-776898b7c796"
Template: "a31bcb73-20a9-4bc2-91d8-776898b7c796"
Path: /sitecore/templates/Project/Hackathon/_Hackathon Contest Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T063559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
