---
ID: "3662eff8-e0ea-49b5-bccd-8be166cefc6f"
Parent: "7e257750-f6b8-4c07-b353-5d789b2b6bde"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/Hackathon/_Hackathon Settings/Hackathon Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T120733Z
