---
ID: "bad8365c-b026-4364-a83c-0b4429934b5d"
Parent: "2f8cbaa0-8100-4c23-8606-bd37ff9bc52f"
Template: "2f8cbaa0-8100-4c23-8606-bd37ff9bc52f"
Path: /sitecore/templates/Project/Hackathon/Topic/Topic Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{7AD85045-9861-42FC-83E5-64A3442F579F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T055425Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
