---
ID: "0e9c933f-01e5-4787-91b6-ee3f2b8798b6"
Parent: "1e6deccd-e3ab-4dda-a9c0-483d47e10382"
Template: "1e6deccd-e3ab-4dda-a9c0-483d47e10382"
Path: /sitecore/templates/Project/Hackathon/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052033Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
