---
ID: "bbda3fa0-613e-4688-a7b5-82f49bd26dbc"
Parent: "55ed4715-ee72-40c1-ada0-ff584f503020"
Template: "55ed4715-ee72-40c1-ada0-ff584f503020"
Path: /sitecore/templates/Project/Hackathon/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052033Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
