---
ID: "d752928d-105a-439b-8abd-da313f9b33f8"
Parent: "767afbd3-1741-47cc-b0a0-d3bba5de5bfd"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Hackathon/Hackathon/Settings/Datasource Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052501Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
